[pre-commit.commands.lint]
run = "pnpm exec oxlint --fix {staged_files}"
glob = "*.{js,mjs,cjs,ts,mts,cts,jsx,tsx,astro,svelte,vue}"
stage_fixed = true

[pre-commit.commands.format]
run = "pnpm exec oxfmt --write {staged_files}"
stage_fixed = true
